backend:
  name: git-gateway
  branch: master  

media_folder: "uploads"        # Folder inside the repo for storing uploaded files
public_folder: "/uploads"      # Public URL path

site_url: https://fda-elibrarygh.netlify.app  # ✅ Your actual deployed URL
logo_url: /assets/fda-logo.png                # ✅ Matches your real logo path

collections:
  - name: "books"
    label: "Books"
    folder: "content/books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: [
            "Admin",
            "Finance",
            "Laboratory",
            "Food Safety",
            "Public Health",
            "Medical Devices",
            "Drug Development",
            "FDA Regulations",
            "Research & Reports",
            "Consumer Education",
            "Compliance & Policies",
            "Tobacco & Substances Abuse",
            "Cosmetic & Household Medicals"
          ]
        }
      - { label: "Description", name: "description", widget: "text", required: false }
      - {
          label: "Book File (PDF)",
          name: "file",
          widget: "file",
          media_library: { allow_multiple: false },
          required: true
        }

  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }